version: '2'
services:
  dga_predict:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - "./src:/dga_predict"
    environment:
      - MAX_BIGRAM_EPOCH=1
      - MAX_LSTM_EPOCH=1
      - FORCE=1
